FROM python:3.11-slim

WORKDIR /app

# On copie et installe les dépendances nécessaires (comme requests)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# On injecte le script de simulation et le fichier de données CSV
COPY lanceur_tfc.py .
COPY creditcard.csv .

# Commande pour démarrer automatiquement la simulation de flux
CMD ["python", "lanceur_tfc.py"]